// SPDX-FileCopyrightText: 2021 Thomas Mathys
// SPDX-License-Identifier: MIT
//
// Code size (bytes)                Description. Note: code in header does not count towards size.
// --------------------------------------------------------------------------------------------------------------------
// 220                  n/a         Original prototype written in assembly. Does not restore sp. No code in header.
// 224                  59c796b     First version generated by this file. Does not restore sp. No code in header.
//                                  Using unoptimized ldr instructions to load load address and entry point from pool.
// 228                  fe2a520     Restore sp to 0x03007f00 before executing unpacked intro. No code in header.
// 228                  e093da7     Code unlikely to vary is at the beginning of the ROM. No code in header.
// 200                  50f0d25     Moved code into header (getkind and the beginning of getbit).
//
// The Thumb Shrinkler depacker is a pretty direct port of the 68k depacker,
// including how the contexts are laid out on the stack. This is somewhat
// non-obvious, but Blueberry gave a nice explanation of this on the A.D.A.
// coding forum: https://ada.untergrund.net/?p=boardthread&id=264&page=4#msg10080
//
// It is reproduced here:
//
//   "D6 is usually positive - it is only negative in the single case of
//   reading the bit indicating whether a reference uses a repeated offset
//   or not. This bit has a context separate from all the others.
//   It happens where there is the 'moveq.l #-1,d6' instruction.
//
//   The instructions calculating the address into the stack
//   ('lea.l 4+SINGLE_BIT_CONTEXTS*2(a7,d6.l),a1' and then 'add.l d6,a1')
//   add 4 to get past the return address of the GetBit call, plus another 2
//   to make room for that single bit context mentioned earlier.
//   This way, the address always ends up into the space allocated on the stack.
//
//   The upper byte of D6 is set separately from the lower byte. It happens
//   both in the GetKind and GetNumber procedures, in both cases using the
//   'lsl.w #8,d6' instruction. The upper byte groups the contexts,
//   so they are ordered like this:
//
//   * -1: Repeated offset (as described above)
//   * $000: Literal/match select for even bytes
//   * $0xx: Literal contexts for even bytes
//   * $100: Literal/match select for odd bytes
//   * $1xx: Literal contexts for odd bytes
//   * $3xx: Number contexts for match offsets
//   * $4xx: Number contexts for match lengths
//
//   The reason for skipping $2xx is that the number contexts are accessed
//   through the GetNumber function, which means there will be one more
//   return address on the stack once the execution reaches GetBit,
//   so the effective base address of the context table will be 4 bytes
//   earlier when accessing the number contexts.
//   Thus, $2xx would overlap the $1xx contexts slightly.
//   The easiest (i.e. smallest) way to compensate is simply to not use $2xx.
//   Also the number contexts don't use the whole ranges
//   (only up to 30 at max in the lower byte). So it should be possible to
//   reduce the number of contexts used to less than 600, though that would
//   make the computation of the context index more involved."

module;

#include <bit>
#include <concepts>
#include <cstdint>
#include <gsl/gsl>
#include <lzasm/arm/arm32/divided_thumb_assembler.hpp>
#include <string>

module shrinkler_gba;
import :utility;
import libshrinkler;

namespace shrinkler_gba
{

using namespace lzasm::arm::arm32;
using namespace std::literals::string_literals;

namespace
{

constexpr auto initial_sp = 0x03007f00;

// GBA register addresses
constexpr uint32_t reg_base = 0x04000000;
constexpr uint32_t reg_dispcnt = reg_base + 0x00;

// DISPCNT bits
constexpr uint32_t mode_4 = 4;
constexpr uint32_t bg2_on = 1 << 10;

// Register aliases
constexpr auto inp = r0;        // Compressed data
constexpr auto outp = r1;       // Decompressed data
constexpr auto tmp0 = r2;       // Scratch register 0
constexpr auto tmp1 = r3;       // Scratch register 1
constexpr auto rvalue = r4;     // Range value
constexpr auto isize = r5;      // Interval size
constexpr auto bitbuf = r6;     // Input bit buffer
constexpr auto bitctx = r7;     // Bit context index
constexpr auto offset = r8;     // Offset
constexpr auto saved_sp = r9;   // Saved stack pointer

constexpr bool is_power_of_2(std::unsigned_integral auto n)
{
    return std::popcount(n) == 1;
}

constexpr uint32_t rgb5(uint32_t r, uint32_t g, uint32_t b)
{
    return r | (g << 5) | (b << 10);
}

constexpr uint32_t rgb8(uint32_t r, uint32_t g, uint32_t b)
{
    return rgb5(r >> 3, g >> 3, b >> 3);
}

class shrinkler_cartridge_assembler final : private cartridge_assembler
{
public:
    shrinkler_cartridge_assembler(const input_file& input_file, const bytevector& compressed_program, const shrinkler_packer_options& options)
        : m_options(options)
    {
        m_data = assemble(input_file, compressed_program);

        // If we have no code in the header then we can use header fields normally and calculate and patch the complement field.
        //
        // If we do have code in the header, the complement field is part of a harmless bogus opcode that we inserted there.
        // It is a "mov rn,xx" instruction, where the complement field encodes the "mov rn" part. As destination register we
        // choose a register that we do not use and where we do not care that it gets clobbered.
        //
        // The game version field encodes the immediate value ("xx"), which we do not care about and which we can choose freely.
        // So we calculate a value for the game version field like we'd normally to for the complement field and then update
        // the game version field instead of the complement field.
        write_complement(m_data, m_options.code_in_header ? ofs_game_version : ofs_complement);

        throw_if_fixed_byte_wrong(m_data);
        throw_if_complement_wrong(m_data);
    }

    const bytevector& data() const
    {
        return m_data;
    }

    size_t depacker_size() const
    {
        return m_depacker_size;
    }

private:
    bytevector assemble(const input_file& input_file, const bytevector& compressed_program)
    {
        // 1536 contexts would be sufficient, but 2048 is smaller.
        constexpr auto INIT_ONE_PROB = 0x8000u;
        constexpr auto ADJUST_SHIFT = 4;
        constexpr auto SINGLE_BIT_CONTEXTS = 1;
        constexpr auto NUM_CONTEXTS = 2048u;

        constexpr auto getnumber_push_list = make_push_list(outp, lr);
        constexpr auto getbit_push_list = make_push_list(outp, tmp0, tmp1, lr);

        // Offset for accessing the context table relative to SP.
        constexpr auto CTX_TABLE_OFFSET = 4 * getbit_push_list.size() + 4 * getnumber_push_list.size() + 2 * SINGLE_BIT_CONTEXTS;

        ////////////////////////////////////////////////////////////////////////////
        // Cartridge header
        ////////////////////////////////////////////////////////////////////////////

        arm_branch("code_start"s);
        emit_nintendo_logo();

        if (!m_options.code_in_header)
        {
            emit_remaining_header();
        }

        // We're still inside the cartridge header, but most of the remaining fields
        // can be abused to stick code into them, so we'll just do that.

        ////////////////////////////////////////////////////////////////////////////
        // getkind: figure out whether the next symbol is a literal or a reference
        // In:  Nothing, sets up bitctx itself
        // Out: C = 0 if the next symbol is a literal, C = 1 if it is a reference
        //      bitctx = parity
        ////////////////////////////////////////////////////////////////////////////
        throw_if_not_aligned(1);
        align(1);
    label("getkind"s);
        // Use parity as context : bitctx = (outp & 1) << 8
        lsl(bitctx, outp, 31);
        lsr(bitctx, bitctx, 23);
        // Fall through into getbit

        ////////////////////////////////////////////////////////////////////////////
        // getbit: decode a single bit
        // In:       bit context index in bitctx
        // Out:      Bit in C. That is, C=1 is a bit with value 1.
        // Destroys: bitctx
        // Keeps its state in bitbuf, isize and rvalue. So these must not be modified.
        ////////////////////////////////////////////////////////////////////////////
    label("getbit"s);
        push(getbit_push_list);
        b("loop_condition"s);
    label("readbit"s);
        lsl(bitbuf, bitbuf, 1);
        bne("nonewword"s);
    label("newword"s);
        ldr(bitbuf, inp, 0);
        add(inp, 4);
        // Shift data bit into C and make bit 0 the new sentinel bit.
        add(bitbuf, bitbuf);
        if (m_options.code_in_header)
        {
            // Fixed byte of value 0x96, followed by unit code which can be freely chosen.
            // We insert an instruction here that does not bother us and stomp over it.
            throw_if_wrong_lc(ofs_fixed_byte, "fixed byte");
            mov(tmp0, fixed_byte_value);
        }
        mov(tmp0, 1);
        orr(bitbuf, tmp0);
    label("nonewword"s);
        adc(rvalue, rvalue);
        add(isize, isize);
    label("loop_condition"s);
        if (m_options.code_in_header)
        {
            // game version (immediate value), followed by complement (opcode).
            // Again, insert an instruction that does not bother us and stomp over it.
            // Later we need to fix up the immediate value (the game version),
            // so that it matches the complement. We cannot fix up the complement,
            // like we'd normally do, since we'd end up with a random, potentially
            // harmful instruction. See also write_complement().
            constexpr unsigned char dummy_game_version_that_gets_overwritten_later_instead_of_the_complement = 0x77;
            throw_if_wrong_lc(ofs_game_version, "game version");
            mov(tmp0, dummy_game_version_that_gets_overwritten_later_instead_of_the_complement);
        }
        lsr(tmp0, isize, 16);         // Loop while bit 15 is clear
        bcc("readbit"s);

        // Context is at : SP + CTX_TABLE_OFFSET + 2 * bitctx
        add(tmp0, bitctx, bitctx);
        add(tmp0, sp);

        // tmp1 = probability
        ldrh(tmp1, tmp0, CTX_TABLE_OFFSET);

        // outp = threshold = (intervalsize * prob) >> 16
        mov(outp, tmp1);
        mul(outp, isize);
        lsr(outp, outp, 16);

        // prob = prob - (prob >> ADJUST_SHIFT)
        lsr(bitctx, tmp1, ADJUST_SHIFT);
        sub(tmp1, tmp1, bitctx);

        sub(rvalue, rvalue, outp);
        bcc("one"s);
    label("zero"s);
        sub(isize, isize, outp);      // intervalsize -= threshold
        add(tmp1, 0);                 // C = 0, bit = 0
        b("done"s);
    label("one"s);
        mov(isize, outp);
        ldr(bitctx, 0xffff >> ADJUST_SHIFT);
        add(tmp1, bitctx);
        add(rvalue, outp);            // C = 1, bit = 1
    label("done"s);
        strh(tmp1, tmp0, CTX_TABLE_OFFSET);
        pop(to_pop_list(getbit_push_list));

        ////////////////////////////////////////////////////////////////////////////
        // Main decompression code
        ////////////////////////////////////////////////////////////////////////////

        // Entry point. Initially the GBA is in ARM state.
        // Immediately switch to Thumb state and save sp.
        throw_if_not_aligned(2);
        align(2);
    label("code_start"s);
        arm_to_thumb(inp);
        mov(saved_sp, sp);

        // Initialize input and output pointers.
        adr(inp, "packed_intro"s);
        ldr(outp, gsl::narrow<int32_t>(input_file.load_address()));

        // Initialize range decoder state.
        // rvalue will be set to 0 by the loop that follows.
        mov(isize, 1);
        lsl(bitbuf, isize, 31);

        // Initialize probabilities, writing two contexts per iteration.
        static_assert(is_power_of_2(NUM_CONTEXTS), "NUM_CONTEXTS must be a power of 2");
        static_assert(is_power_of_2(INIT_ONE_PROB), "INIT_ONE_PROB must be a power of 2");
        lsl(rvalue, isize, std::countr_zero(NUM_CONTEXTS / 2)); // rvalue = NUM_CONTEXTS / 2
        lsl(bitctx, isize, std::countr_zero(INIT_ONE_PROB));    // bitctx = (INIT_ONE_PROB << 16) | INIT_ONE_PROB
        orr(bitctx, bitbuf);
    label("init"s);
        push(bitctx);
        sub(rvalue, 1);
        bne("init"s);
        // Now rvalue is 0

        // Main decompression loop.
    label("literal"s);
        mov(tmp0, 1);
    label("getlit"s);
        lsl(bitctx, outp, 31);        // bitctx = ((outp & 1) << 8) | current_byte
        lsr(bitctx, bitctx, 23);
        orr(bitctx, tmp0);
        bl("getbit"s);
        adc(tmp0, tmp0);
        cmp(tmp0, 255);
        bls("getlit"s);
        strb(tmp0, outp, 0);
        add(outp, 1);
    label("switch"s);
        // After literal
        bl("getkind"s);
        bcc("literal"s);
        // Reference
        mov(bitctx, 0);               // bitctx = -1
        sub(bitctx, 1);
        bl("getbit"s);
        bcc("readoffset"s);
    label("readlength"s);
        mov(tmp0, 4);
        bl("getnumber"s);
        mov(tmp0, offset);
        neg(tmp0, tmp0);
    label("copyloop"s);
        ldrb(bitctx, outp, tmp0);
        strb(bitctx, outp, 0);
        add(outp, 1);
        sub(tmp1, 1);
        bne("copyloop"s);
        // After reference
        bl("getkind"s);
        bcc("literal"s);
    label("readoffset"s);
        mov(tmp0, 3);
        bl("getnumber"s);
        sub(tmp1, 2);
        mov(offset, tmp1);
        bne("readlength"s);
    label("donedecompressing"s);
        mov(sp, saved_sp);
        debug_check_decompressed_data_size(input_file);
        debug_check_decompressed_data(input_file);
        debug_check_sp_on_exit();
        ldr(outp, gsl::narrow<int32_t>(input_file.entry()));
        bx(outp);

        ////////////////////////////////////////////////////////////////////////////
        // getnumber: decode variable length number
        // In:  tmp0 = Base context / 256. That is, call with tmp0 = 3 or tmp0 = 4.
        // Out: tmp1 = Number
        ////////////////////////////////////////////////////////////////////////////
    label("getnumber"s);
        push(getnumber_push_list);
        lsl(tmp0, tmp0, 8);
        mov(outp, 0);
    label("numberloop"s);
        add(outp, 2);
        mov(bitctx, tmp0);
        orr(bitctx, outp);
        bl("getbit"s);
        bcs("numberloop"s);
        mov(tmp1, 1);
        sub(outp, 1);
    label("bitsloop"s);
        mov(bitctx, tmp0);
        orr(bitctx, outp);
        bl("getbit"s);
        adc(tmp1, tmp1);
        sub(outp, 2);
        bcs("bitsloop"s);
        pop(to_pop_list(getnumber_push_list));
        pool();

        ////////////////////////////////////////////////////////////////////////////
        // Compressed intro.
        // Must be word aligned, since
        // * The packer reads entire words from the bitstream.
        // * We use adr to load the address to the packed data,
        //   which requires word alignment.
        ////////////////////////////////////////////////////////////////////////////
        align(2);
        m_depacker_size = current_lc() - gba_header_size;
    label("packed_intro"s);
        incbin(compressed_program.begin(), compressed_program.end());
        debug_emit_panic_routine();
        return link(rom_start);
    }

    // Macro that calls the panic routine if the size of the decompressed data is incorrect.
    // This macro expects outp (the output pointer) to point to the byte after the last decompressed byte.
    // This macro clobbers all registers except sp.
    void debug_check_decompressed_data_size(const input_file& input_file)
    {
        if (!m_options.debug_checks)
        {
            return;
        }

        // outp = outp - load_address = actual number of bytes depacked
        ldr(tmp1, gsl::narrow<int32_t>(input_file.load_address()));
        sub(outp, outp, tmp1);

        // Compare actual with expected number of bytes depacked
        ldr(tmp1, gsl::narrow<int32_t>(input_file.loaded_data_size()));
        cmp(outp, tmp1);
        beq("decompressed_data_size_ok"s);
        debug_call_panic_routine("Wrong decompressed data size\n");
    label("decompressed_data_size_ok"s);
    }

    // Macro that calls the panic routine if the checksum of the decompressed data is incorrect.
    // This macro clobbers all registers except sp.
    void debug_check_decompressed_data(const input_file& input_file)
    {
        if (!m_options.debug_checks)
        {
            return;
        }

        constexpr auto decompressed_data = r0;
        constexpr auto s1 = r1;
        constexpr auto s2 = r2;
        constexpr auto loop_counter = r3;
        constexpr auto byte = r4;
        constexpr auto base = r5;
        constexpr auto expected_checksum = r6;

        // Calculate adler32 checksum of depacked data
        ldr(base, 65521);
        ldr(decompressed_data, gsl::narrow<int32_t>(input_file.load_address()));
        mov(s1, 1);
        mov(s2, 0);
        ldr(loop_counter, gsl::narrow<int32_t>(input_file.loaded_data_size()));
    label("adler32_loop"s);
        ldrb(byte, decompressed_data, 0);
        add(s1, byte);
        cmp(s1, base);
        blo("s1_ok"s);
        sub(s1, s1, base);
    label("s1_ok"s);
        add(s2, s1);
        cmp(s2, base);
        blo("s2_ok"s);
        sub(s2, s2, base);
    label("s2_ok"s);
        add(decompressed_data, 1);
        sub(loop_counter, 1);
        bne("adler32_loop"s);
        lsl(s2, s2, 16);
        orr(s1, s2);

        // Compare expected and actual checksum
        ldr(expected_checksum, to_signed(adler32(input_file.data())));
        cmp(s1, expected_checksum);
        beq("checksum_ok"s);
        debug_call_panic_routine("Wrong decompressed data checksum\n");
    label("checksum_ok"s);
    }

    // Macro that calls the panic routine if the stack pointer has not been restored to its initial value.
    // This macro clobbers all registers.
    void debug_check_sp_on_exit()
    {
        if (!m_options.debug_checks)
        {
            return;
        }

        ldr(r0, initial_sp);
        cmp(r0, sp);
        beq("sp_ok"s);
        debug_call_panic_routine("Wrong sp after depacking\n");
    label("sp_ok"s);
    }

    // Macro that calls the panic routine. The panic routine clobbers all registers and does not return.
    void debug_call_panic_routine(const std::string& message)
    {
        if (!m_options.debug_checks)
        {
            return;
        }

        adr(r2, message);
        bl("panic"s);

        // Embed panic message.
        // Note 1: the adr pseudo op requires word alignment.
        // Note 2: since lzasm does not support local labels we use the message itself
        //         also as label name. This is obviously totally awful, but works
        //         as long as the macro is not called twice with the same message.
        align(2);
    label(message);
        asciz(message);

        // Align for subsequent thumb code.
        align(1);
    }

    // Macro that emits the panic routine. The panic routine clobbers all registers and does not return.
    // The panic routine must be called with r2 pointing to a zero terminated error message.
    // This message will be printed using Mappy / VisualBoyAdvance debug output.
    void debug_emit_panic_routine()
    {
        if (!m_options.debug_checks)
        {
            return;
        }

        align(1);
    label("panic"s);

        // Print panic message using Mappy / VisualBoyAdvance debug output.
        // r2 must point to a zero terminated string.
        ldr(r0, to_signed(0xc0ded00d));
        mov(r1, 0);
        and_(r0, r0);

        // Set video mode
        ldr(r0, mode_4 | bg2_on);
        ldr(r1, reg_dispcnt);
        str(r0, r1, 0);

        // Set palette
        // Set color 0 and 1 using a single 32 bit write
        ldr(r0, (rgb8(255, 255, 255) << 16) | rgb8(0, 119, 215));
        ldr(r1, bg_palette_start);
        str(r0, r1, 0);

        // Draw sad face
        adr(r0, "sadface"s);
        ldr(r1, vram_start + 4 * 240 + 4);
        mov(r4, 8);             // Copy 8 lines
    label("copy_line"s);
        ldmia(!r0, r2 - r3);    // Read 8 pixels
        stmia(!r1, r2 - r3);    // Write 8 pixels
        add(r1, 240 - 8);       // Move to next line
        sub(r4, r4, 1);
        bne("copy_line"s);

        // Halt system
    label("loop"s);
        b("loop"s);

        // 8x8 8bpp image of sad face
        align(2);
    label("sadface"s);
        byte(0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00);
        byte(0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01);
        byte(0x01, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01);
        byte(0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01);
        byte(0x01, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01);
        byte(0x01, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0x01);
        byte(0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01);
        byte(0x00, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x00);
        pool();
    }

    const shrinkler_packer_options m_options;
    bytevector m_data;
    size_t m_depacker_size{};
};

bytevector compress(const bytevector& uncompressed_binary, const shrinkler_packer_options& options, libshrinkler::compression_info& ci)
{
    using namespace libshrinkler;

    encoder_parameters parameters = options.encoder_parameters;
    parameters.endianness(endianness::little);

    // Note: we could experiment with disabling the parity context,
    // but so far I have not seen a binary where that yielded better compression.
    // Moreover we'd have to use an alternate depacker.
    encoder encoder;
    encoder.parameters(parameters);

    return encoder.encode(uncompressed_binary, ci);
}

cartridge assemble_cartridge(const input_file& input_file, const bytevector& compressed_binary, const shrinkler_packer_options& options)
{
    shrinkler_cartridge_assembler assembler(input_file, compressed_binary, options);
    return cartridge
    {
        .packer = "Shrinkler",
        .data = assembler.data(),
        .compressed_size = compressed_binary.size(),
        .depacker_size = assembler.depacker_size()
    };
}

}

cartridge shrinkler_packer::pack(const input_file& input_file)
{
    libshrinkler::compression_info ci;
    auto compressed_binary = compress(input_file.data(), m_options, ci);

    auto cartridge = assemble_cartridge(input_file, compressed_binary, m_options);

    if (ci.increase_reference_buffer_hint)
    {
        cartridge.info.push_back("Shrinkler compression may benefit from a larger reference buffer (-r option)");
    }

    return cartridge;
}

}
