// shrinkler-gba: Port of the Shrinkler Amiga executable cruncher for the GBA
//
// Code size (bytes)                Description. Note: code in header does not count towards size.
// --------------------------------------------------------------------------------------------------------------------
// 220                  n/a         Original prototype written in assembly. Does not restore sp. No code in header.
// 224                  59c796b     First version generated by this file. Does not restore sp. No code in header.
//                                  Using unoptimized ldr instructions to load load address and entry point from pool.
// 228                  fe2a520     Restore sp to 0x03007f00 before executing unpacked intro. No code in header.
// 228                  e093da7     Code unlikely to vary is at the beginning of the ROM. No code in header.
// 200                  50f0d25     Moved code into header (getkind and the beginning of getbit).
//
// The Thumb Shrinkler depacker is a pretty direct port of the 68k depacker,
// including how the contexts are laid out on the stack. This is somewhat
// non-obvious, and Blueberry gave a nice explanation of this on the A.D.A.
// coding forum. It can be found in 3rdparty/Shrinkler/DepackerExplained.md.

#include <bit>
#include "shrinklergbacore/adler32.hpp"
#include "shrinklergbacore/cart_assembler.hpp"
#include "shrinklergbacore/complement.hpp"
#include "shrinklergbacore/gba.hpp"

namespace shrinklergbacore
{


}
